### PR TITLE
[#2711] fix(spark): Race condition on deferred compressed block initialization

### LINKED ISSUE #2711: [Flaky Test] org.apache.uniffle.test.GetShuffleReportForMultiPartTest
### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
[2026-01-13 02:52:09.018] [client-data-transfer-3] [WARN] ShuffleWriteClientImpl.lambda$sendShuffleDataAsync$5 - Send: 49 blocks to [10.1.0.134-60017] failed.
java.lang.NullPointerException
        at org.apache.uniffle.client.impl.grpc.ShuffleServerGrpcClient.sendShuffleData(ShuffleServerGrpcClient.java:576)
        at org.apache.uniffle.client.impl.ShuffleWriteClientImpl.lambda$sendShuffleDataAsync$5(ShuffleWriteClientImpl.java:214)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.578 s <<< FAILURE! - in org.apache.uniffle.test.GetShuffleReportForMultiPartTest
Error:  resultCompareTest  Time elapsed: 11.399 s  <<< ERROR!
org.apache.spark.SparkException: 
Job aborted due to stage failure: Task 4 in stage 1.0 failed 1 times, most recent failure: Lost task 4.0 in stage 1.0 (TID 14) (runnervmi13qx.m4k4wa1psnoergown2ffm0edlg.yx.internal.cloudapp.net executor driver): org.apache.uniffle.common.exception.RssSendFailedException: Fail to send the block. Error: INTERNAL_ERROR
	at org.apache.spark.shuffle.writer.RssShuffleWriter.checkDataIfAnyFailure(RssShuffleWriter.java:585)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.checkBlockSendResult(RssShuffleWriter.java:534)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.writeImpl(RssShuffleWriter.java:392)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.write(RssShuffleWriter.java:338)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Actions URL

https://github.com/apache/uniffle/actions/runs/20942477304/job/60178656211

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

Fix race condition on deferred compressed block initialization

### Why are the changes needed?

fix #2711 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing unit tests

### CODE REVIEW

File: common/src/main/java/org/apache/uniffle/common/DeferredCompressedBlock.java [hunk 1]
```diff
@@ -31,7 +32,7 @@
 public class DeferredCompressedBlock extends ShuffleBlockInfo {
   private final Function<DeferredCompressedBlock, DeferredCompressedBlock> rebuildFunction;
   private int estimatedCompressedSize;
-  private boolean isInitialized = false;
+  private AtomicBoolean isInitialized = new AtomicBoolean(false);
```
Comment (xianjingfeng) [inline common/src/main/java/org/apache/uniffle/common/DeferredCompressedBlock.java:35]: Is this change still needed after using synchronized?

**Comment by xianjingfeng** [comment]
Could you explain the reason for this issue? @zuston

File: common/src/main/java/org/apache/uniffle/common/DeferredCompressedBlock.java (hunk 1 above)
Comment (zuston) [reply common/src/main/java/org/apache/uniffle/common/DeferredCompressedBlock.java:35]: I use the double-lock to ensure the rebuilding happen only once, maybe this is not necessary to make this var sync.

**Comment by zuston** [comment]
> Could you explain the reason for this issue? @zuston

This bug only happens when the overlapping compression is enabled, this will be modified by the multi threads at the same time

**Comment by xianjingfeng** [comment]
> > Could you explain the reason for this issue? @zuston
> 
> This bug only happens when the overlapping compression is enabled, this will be modified by the multi threads at the same time

What I don't understand is why `block.data` would be null in a multi-threaded environment. Even with repeated calls to the `rebuildFunction` function, `block.data` is only overwritten, not set to null.

**Comment by zuston** [comment]
> > > Could you explain the reason for this issue? @zuston
> > 
> > 
> > This bug only happens when the overlapping compression is enabled, this will be modified by the multi threads at the same time
> 
> What I don't understand is why `block.data` would be null in a multi-threaded environment. Even with repeated calls to the `rebuildFunction` function, `block.data` is only overwritten, not set to null.

Got your thought, I haven't found the root cause.

**Review by xianjingfeng — APPROVED** [review]

**Comment by zuston** [comment]
thanks. @xianjingfeng @jerqi let me merge this
