### PR TITLE
[#2298] fix(server): Correct the metric of grpc_get_local_shuffle_data_process_latency

### LINKED ISSUE #2298: [Bug] Incorrect grpc metric of grpc_get_local_shuffle_data_process_latency
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

As title described

### Affects Version(s)

master

### Uniffle Server Log Output

_No response_

### Uniffle Engine Log Output

_No response_

### Uniffle Server Configurations

_No response_

### Uniffle Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

Correct the metric of grpc_get_local_shuffle_data_process_latency

### Why are the changes needed?

fix #2298

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Needn't

### CODE REVIEW

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java [hunk 1]
```diff
@@ -1198,6 +1198,12 @@ public void getLocalShuffleData(
                       offset,
                       length,
                       storageId);
+          reply =
+              GetLocalShuffleDataResponse.newBuilder()
+                  .setStatus(status.toProto())
+                  .setRetMsg(msg)
+                  .setData(UnsafeByteOperations.unsafeWrap(sdr.getData()))
```
Comment (zuston) [inline server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:1205]: the operation of `sdr.getData()` will cost too much time, so it should be scoped into the metrics recording

Comment (jerqi) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:1205]: Got it.

**Review by jerqi — APPROVED** [review]
LGTM.
