### PR TITLE
Flaky Test: LowestIOSampleCostSelectStorageStrategyTest#selectStorageTest

### LINKED ISSUE #526: Flaky Test: LowestIOSampleCostSelectStorageStrategyTest#selectStorageTest
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.844 s <<< FAILURE! - in org.apache.uniffle.coordinator.strategy.storage.LowestIOSampleCostSelectStorageStrategyTest
Error:  selectStorageTest  Time elapsed: 7.611 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <hdfs://p2> but was: <hdfs://p1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at org.apache.uniffle.coordinator.strategy.storage.LowestIOSampleCostSelectStorageStrategyTest.selectStorageTest(LowestIOSampleCostSelectStorageStrategyTest.java:138)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4043459641/jobs/6952402959#step:6:2486

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

1. The way to write mini hdfs has been removed, which is consistent with `AppBalanceSelectStorageStrategyTest`. 
2. Closing the scheduling thread for writing the hdfs file.
3.  Using `CountDownLatch` instead of `thread.join()`.

### Why are the changes needed?

To resolve #526 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Fix ut.

### CODE REVIEW

**Review by kaijchen — COMMENTED** [review]
Thanks for fixing this @smallzhongfeng.
Please add a `@Timeout()` tag after `@Test`.
In case of `cdl.await()` never return.

**Comment by smallzhongfeng** [comment]
> Thanks for fixing this @smallzhongfeng. Please add a `@Timeout()` tag after `@Test`. In case of `cdl.await()` never return.

Good idea, added.

File: coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java [hunk 1]
```diff
@@ -103,19 +83,19 @@ public void selectStorageTest() throws Exception {
...
+    assertEquals(0, applicationManager.getRemoteStoragePathRankValue().get(remoteStorage2).getAppNum().get());
 
     // compare with two remote path
     applicationManager.incRemoteStorageCounter(remoteStorage1);
     applicationManager.incRemoteStorageCounter(remoteStorage1);
     String testApp1 = "application_test_" + 1;
     applicationManager.registerApplicationInfo(testApp1, "user");
     applicationManager.refreshAppId(testApp1);
+    selectStorageStrategy.sortPathByRankValue(remoteStorage2, testFile, System.currentTimeMillis());
     Thread.sleep(1000);
```
Comment (kaijchen) [inline coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:97]: Why do we need to sleep between two `sortPathByRankValue()`?

File: coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java [hunk 2]
```diff
@@ -103,19 +83,19 @@ public void selectStorageTest() throws Exception {
...
-    final long current = System.currentTimeMillis();
-    fs.create(path);
-    selectStorageStrategy.sortPathByRankValue(remoteStorage2, testFile, current);
-    fs.create(path);
-    selectStorageStrategy.sortPathByRankValue(remoteStorage1, testFile, current);
+    selectStorageStrategy.sortPathByRankValue(remoteStorage1, testFile, System.currentTimeMillis());
```
Comment (kaijchen) [inline coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:98]: Why do we need to sleep before this line?

Comment (smallzhongfeng) [reply coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:98]: Ensure that the `System.currentTimeMillis()` corresponding to `remoteStorage1` is greater than that of `remoteStorage2`, because under the `IO` policy, this time is used to measure which remote path is selected, and the smaller the time, the better it will be selected.

Comment (smallzhongfeng) [reply coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:98]: This sleep time can actually be set smaller.

Comment (kaijchen) [reply coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:98]: > Ensure that the `System.currentTimeMillis()` corresponding to `remoteStorage1` is greater than that of `remoteStorage2`, because under the `IO` policy, this time is used to measure which remote path is selected, and the smaller the time, the better it will be selected.

Let's add this comment to the code?

**Comment by kaijchen** [comment]
@jerqi @advancedxy @zuston do you want to take a look?

File: coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java (hunk 2 above)
Comment (smallzhongfeng) [reply coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:101]: OK.

Comment (smallzhongfeng) [reply coordinator/src/test/java/org/apache/uniffle/coordinator/strategy/storage/LowestIOSampleCostSelectStorageStrategyTest.java:101]: OK.

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @smallzhongfeng.

**Review by jerqi — APPROVED** [review]
LGTM

**Comment by smallzhongfeng** [comment]
Thanks for your review. @kaijchen @jerqi

**Comment by kaijchen** [comment]
Hi @smallzhongfeng, seems `selectStorageMulThreadTest` is timeout occasionally.
https://github.com/apache/incubator-uniffle/actions/runs/4184426217/jobs/7250404544#step:6:614

**Comment by smallzhongfeng** [comment]
I think we need to increase this time? @kaijchen WDYT?
