### PR TITLE
[ISSUE-509] Fix Flaky Test: ShuffleBufferManagerTest#shuffleFlushThreshold

### LINKED ISSUE #509: Flaky Test: ShuffleBufferManagerTest#shuffleFlushThreshold
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.198 s <<< FAILURE! - in org.apache.uniffle.server.buffer.ShuffleBufferManagerTest
Error:  shuffleFlushThreshold  Time elapsed: 1.035 s  <<< FAILURE!
Error:  Failures: 
Error:    ShuffleBufferManagerTest.shuffleFlushThreshold:603 expected: <159> but was: <105>
Error:  Tests run: 70, Failures: 1, Errors: 0, Skipped: 0
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4005292106/jobs/6875476922

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

 The reason is that the flush operation is asynchronous, the first block maybe been flushed when judging the memory size.
So the solution is to support active trigger flush.

### Why are the changes needed?

Fix #509 Flaky Test: ShuffleBufferManagerTest#shuffleFlushThreshold.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need

### CODE REVIEW

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 1]
```diff
@@ -67,6 +67,7 @@ public class ShuffleFlushManager {
   private final long pendingEventTimeoutSec;
   private int processPendingEventIndex = 0;
   private final int maxConcurrencyOfSingleOnePartition;
+  private boolean isSuspend;
```
Comment (kaijchen) [inline server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:70]: Add `volatile`?

**Review by kaijchen — COMMENTED** [review]
Thanks for the fix @xianjingfeng, some nits here.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java (hunk 1 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java]: Done

**Review by zuston — COMMENTED** [review]
Could you help describe more about this fix in description? From current code, this fix looks a little bit strange.

**Comment by xianjingfeng** [comment]
> Could you help describe more about this fix in description? From current code, this fix looks a little bit strange.

Because the flush operation is asynchronous, the first block maybe been flushed when judging the memory size.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 2]
```diff
@@ -95,6 +96,10 @@ public ShuffleFlushManager(ShuffleServerConf shuffleServerConf, String shuffleSe
       while (true) {
         try {
           ShuffleDataFlushEvent event = flushQueue.take();
+          // Only for test
+          while (isSuspend) {
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:100]: You are right. Do you have any good ideas?

[the remark this answers is not in the document]
Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:100]: Thanks for the investigation @advancedxy, I prefer the 2nd way. It's always better to improve testability.
If this test fails very often, we can merge this PR first and do the refactor later.

[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java]: Done

**Review by kaijchen — DISMISSED** [review]
LGTM, thanks @xianjingfeng for the fix, and thanks @advancedxy for the review.

File: server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java [hunk 3]
```diff
@@ -567,7 +568,25 @@ public void shuffleFlushThreshold() throws Exception {
...
-        "serverId", mockShuffleServer, storageManager);
+        "serverId", mockShuffleServer, storageManager) {
+
+      @Override
+      protected void startEventProcesser() {
+        // do nothing
+      }
+
+      @Override
+      public void processEvents() {
```
Comment (kaijchen) [inline server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java:579]: I think we shouldn't override `processEvents()`, because if `ShuffleFlushManager#processEvents()` is changed, the test will pass no matter if the change is correct.

**Review by kaijchen — COMMENTED** [review]
Thanks for updating the PR @xianjingfeng. The motivation is good, but here is some concerns.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 4]
```diff
@@ -145,6 +129,31 @@ public void addToFlushQueue(ShuffleDataFlushEvent event) {
     }
   }
 
+  public void processEvents() {
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:132]: No, it will be invoked in UT.

File: server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java [hunk 5]
```diff
@@ -567,7 +568,25 @@ public void shuffleFlushThreshold() throws Exception {
 
     StorageManager storageManager = StorageManagerFactory.getInstance().createStorageManager(conf);
     ShuffleFlushManager shuffleFlushManager = new ShuffleFlushManager(conf,
-        "serverId", mockShuffleServer, storageManager);
+        "serverId", mockShuffleServer, storageManager) {
+
+      @Override
+      protected void startEventProcesser() {
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java:574]: In this UT, if we start EventProcesser, events will be flushed automatically.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 6]
```diff
@@ -137,6 +113,14 @@ public void run() {
     thread.start();
   }
 
+  protected void startEventProcesser() {
+    // the thread for flush data
+    Thread processEventThread = new Thread(() -> processEvents());
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:118]: Got

File: server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/test/java/org/apache/uniffle/server/buffer/ShuffleBufferManagerTest.java]: > https://github.com/apache/incubator-uniffle/pull/510/files/a803bf816ff79e16834ab6f42258373b71e71f5e If you apply this code to your test class method, the event flush could be controlled externally?

Not exactly. At least we can control when to begin flush.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 7]
```diff
@@ -145,6 +134,31 @@ public void addToFlushQueue(ShuffleDataFlushEvent event) {
...
+        threadPoolExecutor.execute(() -> {
+          processEvent(event);
+        });
+      } catch (Exception e) {
+        LOG.error("Exception happened when process event.", e);
+      }
+    }
+  }
+
+  protected void processEvent(ShuffleDataFlushEvent event) {
```
Comment (kaijchen) [inline server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:150]: This method can be private.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 8]
```diff
@@ -145,6 +134,31 @@ public void addToFlushQueue(ShuffleDataFlushEvent event) {
     }
   }
 
+  public void processEvents(boolean endless) {
```
Comment (kaijchen) [inline server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: Maybe we can create another method `eventLoop()`:

```java
  private void startEventProcesser() {
    // the thread for flush data
    Thread processEventThread = new Thread(this::eventLoop);
    processEventThread.setName("ProcessEventThread");
    processEventThread.setDaemon(true);
    processEventThread.start();
  }

  protected void eventLoop() {
    while (true) {
      processEvents();
    }
  }

  public void processEvents() {
    while (!flushQueue.isEmpty()) {
      try {
        ShuffleDataFlushEvent event = flushQueue.take();
        threadPoolExecutor.execute(() -> {
          processEvent(event);
        });
      } catch (Exception e) {
        LOG.error("Exception happened when process event.", e);
      }
    }
  }
```

Then override it in `TestShuffleFlushManager`:
```java
  @Override
  protected void eventLoop() {
    // do nothing
  }
```

**Review by kaijchen — COMMENTED** [review]
Here is some thoughts to further reduce the exposed methods.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java (hunk 8 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]:
```java
protected void eventLoop() {
    while (true) {
      processEvents();
    }
  }

```

The CPU maybe will full?

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java (hunk 7 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:150]: Got

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java (hunk 8 above)
Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]:
```java
while (true) {
  while (!flushQueue.isEmpty()) {
  }
}
```

is same with

```java
while (true || !flushQueue.isEmpty()) {
}
```

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 9]
```diff
@@ -137,6 +108,24 @@ public void run() {
     thread.start();
   }
 
+  protected void startEventProcesser() {
```
Comment (kaijchen) [inline server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:111]: Typo: startEventProcesser -> startEventProcessor

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java (hunk 8 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: Got. But in this pr, if `endless=true`, `flushQueue.take()` will block the thread.

Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: I didn't mean to change the `flushQueue.take()`.

Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: For reference: https://github.com/kaijchen/incubator-uniffle/tree/issue_509_fork

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: I mean `flushQueue.take()` will  block the thread until `flushQueue` is not empty and it will not cost too much cpu resources. But `flushQueue.take()` will not block the thread in the code you implement and  it will not cost a lot of cpu resources.

Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: OK, I got it. If the flushQueue is empty, `processEvents()` will be called again and again.

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: > For reference: https://github.com/kaijchen/incubator-uniffle/tree/issue_509_fork

We need overwrite `startEventProcessor` in `TestShuffleFlushManager`, Because if we start EventProcesser, events will be flushed automatically and this pr is used to prevent automatic flush.

Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: > We need overwrite `startEventProcessor` in `TestShuffleFlushManager`, Because if we start EventProcesser, events will be flushed automatically and this pr is used to prevent automatic flush.

I have fixed the infinite loop and squashed the commits, so you can see all changes in one commit.

Comment (kaijchen) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:137]: Update:
Actually I'm splitting `processEvents()` into `eventLoop()` and `flush()`.

```java
  protected void eventLoop() {
    while (true) {
      processNextEvent();
    }
  }

  @VisibleForTesting
  public void flush() {
    while (!flushQueue.isEmpty()) {
      processNextEvent();
    }
  }

  private void processNextEvent() {
    try {
      ShuffleDataFlushEvent event = flushQueue.take();
      threadPoolExecutor.execute(() -> {
        processEvent(event);
      });
    } catch (Exception e) {
      LOG.error("Exception happened when process event.", e);
    }
  }
```

**Comment by kaijchen** [comment]
Thanks @xianjingfeng  for updating the PR, @advancedxy what do you think?

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 10]
```diff
@@ -50,8 +51,8 @@ public class ShuffleFlushManager {
   private static final Logger LOG = LoggerFactory.getLogger(ShuffleFlushManager.class);
   public static final AtomicLong ATOMIC_EVENT_ID = new AtomicLong(0);
   private final ShuffleServer shuffleServer;
-  private final BlockingQueue<ShuffleDataFlushEvent> flushQueue = Queues.newLinkedBlockingQueue();
-  private final ThreadPoolExecutor threadPoolExecutor;
+  protected final BlockingQueue<ShuffleDataFlushEvent> flushQueue = Queues.newLinkedBlockingQueue();
```
Comment (kaijchen) [inline server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:54]: Please revert this change.

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java]: Done

**Review by zuston — APPROVED** [review]

**Comment by kaijchen** [comment]
Maybe it's better to not expose `flush()` to production code: https://github.com/kaijchen/incubator-uniffle/commit/cb9a0be5734825e9e89f62ff50052ddb32fd90b8

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 11]
```diff
@@ -81,40 +82,10 @@ public ShuffleFlushManager(ShuffleServerConf shuffleServerConf, String shuffleSe
...
-        } catch (Exception e) {
-          LOG.error("Exception happened when process event.", e);
-        }
-      }
-    };
-    Thread processEventThread = new Thread(processEventRunnable);
-    processEventThread.setName("ProcessEventThread");
-    processEventThread.setDaemon(true);
-    processEventThread.start();
+    startEventProcessor();
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java]: Done

**Comment by xianjingfeng** [comment]
> Maybe it's better to not expose `flush()` to production code: [kaijchen@cb9a0be](https://github.com/kaijchen/incubator-uniffle/commit/cb9a0be5734825e9e89f62ff50052ddb32fd90b8)

Done

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java [hunk 12]
```diff
@@ -81,40 +82,10 @@ public ShuffleFlushManager(ShuffleServerConf shuffleServerConf, String shuffleSe
...
 
-    int waitQueueSize = shuffleServerConf.getInteger(
-        ShuffleServerConf.SERVER_FLUSH_THREAD_POOL_QUEUE_SIZE);
-    BlockingQueue<Runnable> waitQueue = Queues.newLinkedBlockingQueue(waitQueueSize);
-    int poolSize = shuffleServerConf.getInteger(ShuffleServerConf.SERVER_FLUSH_THREAD_POOL_SIZE);
-    long keepAliveTime = shuffleServerConf.getLong(ShuffleServerConf.SERVER_FLUSH_THREAD_ALIVE);
-    threadPoolExecutor = new ThreadPoolExecutor(poolSize, poolSize, keepAliveTime, TimeUnit.SECONDS, waitQueue,
-        ThreadUtils.getThreadFactory("FlushEventThreadPool"));
+    threadPoolExecutor = createFlushEventExecutor();
+    startEventProcessor();
```
Comment (kaijchen) [inline server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java:86]: I think line L85-86 should be placed after line L87-88.
Because `storageBasePaths` is accessed in `processEvent() -> flushToFile()`

**Review by kaijchen — CHANGES_REQUESTED** [review]
There is a bug introduced in the last commit.

File: server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java (hunk 12 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java]: Done

**Review by kaijchen — APPROVED** [review]
LGTM, thanks a lot @xianjingfeng.
