### PR TITLE
[ISSUE-456] Avoid removeResources for multiple times

### LINKED ISSUE #456: [Improvement] Avoid removeResources for multiple times
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

If `removeResources` take to much time. NPE will be thrown as follows.

```shell
[ERROR] 2022-12-30 00:43:28,403 clearResourceThread ShuffleTaskManager lambda$new$3 - Exception happened when clear resource for expired application
java.lang.NullPointerException
        at org.apache.uniffle.server.ShuffleTaskManager.removeResources(ShuffleTaskManager.java:479)
        at org.apache.uniffle.server.ShuffleTaskManager.lambda$new$3(ShuffleTaskManager.java:130)
        at java.lang.Thread.run(Thread.java:745)

```

### How should we improve?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?
If `Resource` had been removed, avoid remove twice.

### Why are the changes needed?
When some appIds' removeResource took too much time, the `expiredAppCleanupExecutorService` in ShuffleTaskManager
would check and detect the same appId is expired multiple times. Therefore the same appId might be added to `expiredAppIdQueue` multiple times. This PR fixes #456 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

File: server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java [hunk 1]
```diff
@@ -753,7 +807,8 @@ public void checkAndClearLeakShuffleDataTest(@TempDir File tempDir) throws Excep
     assertTrue(appIdsOnDisk.contains(appId));
 
     // make sure heartbeat timeout and resources are removed
-    Thread.sleep(5000);
+    Awaitility.await().timeout(10, TimeUnit.SECONDS).until(
```
Comment (zuston) [inline server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java:810]: Why this is involved in this PR?

**Review by zuston — COMMENTED** [review]
Overall LGTM, left minor comment

File: server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java (hunk 1 above)
Comment (xianjingfeng) [reply server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java:810]: In original logic, `shuffleTaskInfos.remove(appId)` was invoked after remove all resources, but it was invoked before remove all resources in this pr. It becomes a flaky test in this pr.

**Comment by xianjingfeng** [comment]
> The fix looks good to me. But could you elaborate a bit more in the pr description's `Why are the changes needed` section.
> 
> If I understand the issue and this fix correctly, the reason why some appId is called multiple times is that:
> 
> ```
> When some appIds' removeResource took too much time, the `expiredAppCleanupExecutorService` in ShuffleTaskManager
> would check and detect the same appId is expired multiple times. Therefore the same appId might be added to `expiredAppIdQueue` multiple time.
> ```

Done. Thanks your describe.

**Review by jerqi — APPROVED** [review]
LGTM

**Review by zuston — APPROVED** [review]

**Comment by zuston** [comment]
Merged. Thanks @xianjingfeng @advancedxy @jerqi
