### PR TITLE
[#559] test: use withEnvironmentVariable to replace RssUtilsTest#setEnv

### LINKED ISSUE #559: [Improvement] refactor RssUtilsTest.setEnv by leverage EnvironmentVariables system stub
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently `setEnv` is defined as below
```
  @SuppressWarnings("unchecked")
  public static void setEnv(String key, String value) {
    try {
      Map<String, String> env = System.getenv();
      Class<?> cl = env.getClass();
      Field field = cl.getDeclaredField("m");
      field.setAccessible(true);
      Map<String, String> writableEnv = (Map<String, String>) field.get(env);
      if (value != null) {
        writableEnv.put(key, value);
      } else {
        writableEnv.remove(key);
      }
    } catch (Exception e) {
      throw new IllegalStateException("Failed to set environment variable", e);
    }
  }
```

which is not idiomatic Java. We should use https://www.baeldung.com/java-system-stubs#3-junit-5-environment-variables instead.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by advancedxy**
### What changes were proposed in this pull request?
replace `RssUtils.setEnv` by `withEnvironmentVariable`

### Why are the changes needed?
Better code quality. This fixes #559 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existed UTs.

### CODE REVIEW

**Review by kaijchen — COMMENTED** [review]
Thanks @advancedxy for the work. Some general questions here.

File: common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java [hunk 1]
```diff
@@ -43,7 +46,16 @@
 import static org.junit.jupiter.api.Assertions.assertTrue;
 import static org.junit.jupiter.api.Assertions.fail;
 
-public class RssUtilsTest {
+@ExtendWith(SystemStubsExtension.class)
+public class RssUtilsTest implements EnvironmentVariablesSetter {
```
[the remark this answers is not in the document]
Comment (kaijchen) [reply common/src/test/java/org/apache/uniffle/common/util/RssUtilsTest.java:50]: Can we just declear `@SystemStub private static EnvironmentVariables env;` at every test requires it. And reduce the coupling?

File: server/src/test/java/org/apache/uniffle/server/ShuffleServerConfTest.java [hunk 2]
```diff
@@ -20,22 +20,16 @@
 import java.io.File;
 
 import org.junit.jupiter.api.Test;
-import org.junit.jupiter.api.extension.ExtendWith;
-import uk.org.webcompere.systemstubs.environment.EnvironmentVariables;
-import uk.org.webcompere.systemstubs.jupiter.SystemStub;
-import uk.org.webcompere.systemstubs.jupiter.SystemStubsExtension;
 
 import org.apache.uniffle.common.util.ByteUnit;
+import org.apache.uniffle.storage.EnvTestBase;
```
Comment (kaijchen) [inline server/src/test/java/org/apache/uniffle/server/ShuffleServerConfTest.java:25]: It looks weird to extend a `storage` test from `server` package.

Comment (kaijchen) [reply server/src/test/java/org/apache/uniffle/server/ShuffleServerConfTest.java:25]: New test writers may not be aware of this `EnvTestBase`, because it's hiding in the `storage` package.
And I think this kind of abstraction isn't saving us much work.

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @advancedxy.
