### PR TITLE
[ISSUE-514] Fix flaky test: ShuffleServerGrpcTest#clearResourceTest

### LINKED ISSUE #514: Flaky Test: ShuffleServerGrpcTest#clearResourceTest
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at org.apache.uniffle.test.ShuffleServerGrpcTest.clearResourceTest(ShuffleServerGrpcTest.java:162)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4034605585/jobs/6935945287

### Parent issue

#1733

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Fix flaky test: ShuffleServerGrpcTest#clearResourceTest. Fix #514 

### Why are the changes needed?

It is flaky test.
In this UT, `rss.server.preAllocation.expired=5000`, so `ShuffleTaskManager#checkResourceStatus` will be invoked for every 2.5 seconds and expired app may will not be removed until 7.5 seconds after stop heartbeat. So sleep 8 seconds may not be reliable.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need

### CODE REVIEW

File: integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java [hunk 1]
```diff
@@ -160,7 +160,8 @@ public void clearResourceTest() throws Exception {
 
     // clearResourceTest1 will be removed because of rss.server.app.expired.withoutHeartbeat
     t.interrupt();
-    Awaitility.await().timeout(20, TimeUnit.SECONDS).until(() -> shuffleServers.get(0).getShuffleTaskManager().getAppIds().size() == 0);
+    Awaitility.await().timeout(20, TimeUnit.SECONDS).until(
+        () -> shuffleServers.get(0).getShuffleTaskManager().getAppIds().size() == 0);
     assertEquals(0, shuffleServers.get(0).getShuffleTaskManager().getAppIds().size());
```
Comment (kaijchen) [inline integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerGrpcTest.java:165]: This line is not needed now.
However, it's OK to keep it.

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @xianjingfeng for the fix.
