### PR TITLE
[Bug] Fix potential negative preAllocatedSize variable

### LINKED ISSUE #229: Negative value of preAllocatedSize
I found sometimes the value of  `preAllocatedSize` is negative in the shuffle server log, which makes me confused. Maybe this problem is caused by race condition.

### PR DESCRIPTION
**Pull request by advancedxy**
### What changes were proposed in this pull request?
- update `preAllocatedSize` atomically 
- add a new configuration to trigger ShuffleBufferManager's flushIfNecessary periodically
- tweaks existing UTs

### Why are the changes needed?
`preAllocatedSize` could be negative in prod env and this affects  memory pressure calculation.
And this commit should fix #229 #426.

### Does this PR introduce _any_ user-facing change?
- a new ShuffleServer configuration is introduced

### How was this patch tested?
Existing UTs.

### CODE REVIEW

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java [hunk 1]
```diff
@@ -256,6 +251,9 @@ public void sendShuffleData(SendShuffleDataRequest req,
           break;
         }
       }
+      // since the required buffer id is only used once, the shuffle client would try to require another buffer.
+      // we should remove this require buffer whether the cache shuffle data succeeded or not
+      manager.removeRequireBufferId(requireBufferId);
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:256]: We can't remove it after all blocks cached.

https://github.com/apache/incubator-uniffle/blob/c8f8292ce03d4a0f481759d79e404a3324869612/server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java#L497-L514

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:256]: Another reason:  Pre allocated memory cannot be released in time

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:256]: If all goes well, preAllocated memory will be released when cache block.  but `usedMemory` will be released after flush finish. And `preAllocatedBufferCheck` will release `usedMemory` 
So, if preAllocatedBufferCheck clean the require buffer when caching blocks, `usedMemory` will be released twice.

**Comment by xianjingfeng** [comment]
I think we can solve the problem through lock, like row lock.

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java [hunk 2]
```diff
@@ -193,8 +193,14 @@ public boolean isPreAllocated(long requireBufferId) {
     return requireBufferIds.containsKey(requireBufferId);
   }
 
-  public void removeRequireBufferId(long requireId) {
-    requireBufferIds.remove(requireId);
+  public void removeRequireBufferId(long requireBufferId) {
+    PreAllocatedBufferInfo preAllocatedBuffer = requireBufferIds.remove(requireBufferId);
+    if (preAllocatedBuffer != null) {
+      synchronized (preAllocatedBuffer) {
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:199]: Sorry, i didn't see it just now.

> So, if preAllocatedBufferCheck clean the require buffer when caching blocks, `usedMemory` will be released twice.

But this problem seems to still exist.

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java [hunk 3]
```diff
@@ -226,26 +227,21 @@ public void sendShuffleData(SendShuffleDataRequest req,
         return;
       }
       final long start = System.currentTimeMillis();
+      manager.markBufferInUse(requireBufferId);
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: What will happen if manager.isPreAllocated -> clean require buffer -> manager.markBufferInUse

File: server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java [hunk 4]
```diff
@@ -115,7 +115,9 @@ public StatusCode cacheShuffleData(String appId, int shuffleId,
 
     ShuffleBuffer buffer = entry.getValue();
     long size = buffer.append(spd);
-    updateSize(size, isPreAllocated);
+    if (!isPreAllocated) {
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java:118]: isPreAllocated is always true.

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java [hunk 5]
```diff
@@ -121,6 +124,11 @@ public ShuffleTaskManager(
     leakShuffleDataCheckExecutorService.scheduleAtFixedRate(
         () -> checkLeakShuffleData(), leakShuffleDataCheckInterval,
             leakShuffleDataCheckInterval, TimeUnit.MILLISECONDS);
+    this.triggerFlushExecutorService = Executors.newSingleThreadScheduledExecutor(
+            ThreadUtils.getThreadFactory("triggerShuffleBufferManagerFlush"));
+    triggerFlushExecutorService.scheduleAtFixedRate(
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:129]: Why we need this?

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java (hunk 3 above)
Comment (jerqi) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: The gc time of our server will be a little long. Will it increase the probability of this problem?

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: > Well, this could happen, but in practice it should be extremely rare.

In current codebase, it is extremely rare too.


> Even if the above case happens, the outcome would be double releasing `usedMemory` size which has a safe bet that it will never decreased to less than zero.
It will lead to OOM

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: > Well, this could happen, but in practice it should be extremely rare.

In current codebase, it is extremely rare too.


> Even if the above case happens, the outcome would be double releasing `usedMemory` size which has a safe bet that it will never decreased to less than zero.

It will lead to OOM

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java (hunk 5 above)
Comment (jerqi) [reply server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:129]: Is it only useful for tests?

File: server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java (hunk 4 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java:118]: We can modify the UTs.

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java (hunk 5 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:129]: The method maybe help for you
https://github.com/apache/incubator-uniffle/blob/4bd3af64d9e8460301bf04f4b0db261482f63222/internal-client/src/main/java/org/apache/uniffle/client/impl/grpc/ShuffleServerGrpcClient.java#L354

File: common/src/test/java/org/apache/uniffle/common/GrpcServerTest.java [hunk 6]
```diff
@@ -72,13 +72,14 @@ public void testGrpcExecutorPool() throws Exception {
...
 
-    Thread.sleep(1000L);
+    Thread.sleep(100);
     double activeThreads = grpcMetrics.getGaugeMap().get(GRPC_SERVER_EXECUTOR_ACTIVE_THREADS_KEY).get();
     assertEquals(2, activeThreads);
     double queueSize = grpcMetrics.getGaugeMap().get(GRPC_SERVER_EXECUTOR_BLOCKING_QUEUE_SIZE_KEY).get();
     assertEquals(1, queueSize);
 
     countDownLatch.await();
+    Thread.sleep(100);
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply common/src/test/java/org/apache/uniffle/common/GrpcServerTest.java:82]: We should fix it in a new pr.

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java (hunk 3 above)
Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: Incorrect `preAllocatedSize` has no impact on the server, but Incorrect `usedMemory` has. The reason why i don't rush to repair it is because there may be a big adjustment after #133

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: I mean `preAllocatedSize` should be removed.

Comment (xianjingfeng) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:230]: I mean should we modify the `usedMemory` problem in this pr by the way?

File: server/src/test/resources/server.conf [hunk 7]
```diff
@@ -26,3 +26,4 @@ rss.jetty.http.port 12345
 rss.jetty.corePool.size 64
 rss.server.heartbeat.timeout 1
 rss.server.write.timeout 2000
+rss.server.shuffleBufferManager.trigger.flush.interval 500
```
Comment (jerqi) [inline server/src/test/resources/server.conf:29]: Add a new line.

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java [hunk 8]
```diff
@@ -258,6 +255,10 @@ public void sendShuffleData(SendShuffleDataRequest req,
           break;
         }
       }
+      // since the required buffer id is only used once, the shuffle client would try to require another buffer whether
+      // current connection succeeded or not. Therefore, the preAllocatedBuffer is first get and removed, then after
+      // cacheShuffleData finishes, the preAllocatedSize should be updated accordingly.
+      manager.releasePreAllocatedSize(info.getRequireSize());
```
Comment (jerqi) [inline server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:261]: `info` may be null?

Comment (jerqi) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:261]: Do we release `allocateMemory` in any other places? Is there conflicts if we release the memory here?

Comment (jerqi) [reply server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:261]: OK. @xianjingfeng Do you have another suggestion?

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java [hunk 9]
```diff
@@ -125,6 +128,13 @@ public ShuffleTaskManager(
     leakShuffleDataCheckExecutorService.scheduleAtFixedRate(
         () -> checkLeakShuffleData(), leakShuffleDataCheckInterval,
             leakShuffleDataCheckInterval, TimeUnit.MILLISECONDS);
+    this.triggerFlushExecutorService = Executors.newSingleThreadScheduledExecutor(
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:131]: Should we create it only when triggerFLushInterval>0

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java [hunk 10]
```diff
@@ -125,6 +128,13 @@ public ShuffleTaskManager(
...
+            ThreadUtils.getThreadFactory("triggerShuffleBufferManagerFlush"));
+    if (triggerFLushInterval > 0) {
+      triggerFlushExecutorService.scheduleAtFixedRate(
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:134]: Would it be better to use AscheduleWithFixedDelay?

**Comment by xianjingfeng** [comment]
This solution will reduce the preAllocatedSize release speed. Especially when we use LOCAL_ORDER. So i think we should do a performance test.

**Comment by xianjingfeng** [comment]
> You mean the `preAllocatedSize` doesn't decreased per each `cacheShuffleData` call?

Yes

> Could you elaborate a bit more how `LOCAL_ORDER` would be influenced?

It will reordering the blocks. #293 

> As for performance test, do you have any example job for references?

No special requirements. You can also refer to #293.

**Comment by jerqi** [comment]
I don't think this will be influenced by `LOCAL_ORDER`. `LOCAL_ORDER` don't sort when we cache data.`LOCAL_ORDER` sort when we flush data.

**Comment by xianjingfeng** [comment]
> I don't think this will be influenced by `LOCAL_ORDER`. `LOCAL_ORDER` don't sort when we cache data.`LOCAL_ORDER` sort when we flush data.

If memory is not enough, it will trigger flush.

**Comment by xianjingfeng** [comment]
I'm afraid there will be a problem here. It's better to do a simple test.
https://github.com/apache/incubator-uniffle/blob/53212923328194fafa5ae94aa216ab04f06fbd13/server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java#L192

**Comment by xianjingfeng** [comment]
> > `if (usedMemory.get() - preAllocatedSize.get() - inFlushSize.get() > highWaterMark) { `
> 
> If I understand this code correctly, `usedMemory` is not updated for preAllocated buffer. `inFlushSize` is not related to this PR. `preAllocatedSize` is still decreased but slightly slowly.
> 
> In that sense, it will have less change to trigger flush. Therefore `LOCAL_ORDER` is not influenced?

In original logic, flush will be trigger when cache data, but in this pr, it will be trigger by another rpc request.

**Comment by xianjingfeng** [comment]
> Yeah, that's possible.... But the flush trigger is not non-deterministic anyway, it's trigged by outside's requests, which may vary. I still don't get why this kind of change would affect `LOCAL_ORDER` optimization or bring performance penalty here.

1.If the memory release is slow, the client write speed will be affected.  When I did #159 , i encountered similar problems. 2.`LOCAL_ORDER` will affect performance when cache data, but i am not sure how much impact.
In general, there will be a lot of performance impact if this place is not handled well. So, i think simple test is needed.

**Comment by jerqi** [comment]
> > Yeah, that's possible.... But the flush trigger is not non-deterministic anyway, it's trigged by outside's requests, which may vary. I still don't get why this kind of change would affect `LOCAL_ORDER` optimization or bring performance penalty here.
> 
> 1.If `preAllocatedSize` release is slow, the client write speed will be affected. When I did #159 , i encountered similar problems. 2.`LOCAL_ORDER` will affect performance when cache data, but i am not sure how much impact. In general, there will be a lot of performance impact if this place is not handled well. So, i think simple test is needed.

1. What's the problem which you encounter?
2. `LOCAL_ORDER` won't affect performance when cache data.

**Comment by xianjingfeng** [comment]
> 2\. As mentioned in previous reply, it would cause flush less frequently

Maybe this is the reason that why the client write speed will be affected. It maybe lead to usedMemory release slow. When I did #159, i have try to release memory after cache all data, but i found usedMemory release slow. Maybe i am wrong. I am not sure. This change is dangerous. I suggest you test it. Just suggestion.@jerqi @advancedxy

**Comment by zuston** [comment]
Sorry, I missed this thread. I need some time to surf the commits changelog timeline and currently,  I could only give some of my thoughts.

From my side, I think the mechanism of requiring allocation seems like token bucket algorithm, the most difference is the bucket size depending on the free-memory, which is a dynamic bucket. Based on this, we should use the global lock when releasing or getting, this is the key to solve the problem mentioned in description.

> LOCAL_ORDER is an option and it won't give too much performance impact. Because the blocks that we sort won't be very many and we only compare the taskId that isn't a big key.

+1

**Comment by xianjingfeng** [comment]
> From my side, I think the mechanism of requiring allocation seems like token bucket algorithm, the most difference is the bucket size depending on the free-memory, which is a dynamic bucket. Based on this, we should use the global lock when releasing or getting, this is the key to solve the problem mentioned in description.

+1

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java [hunk 11]
```diff
@@ -579,4 +602,11 @@ void removeShuffleDataSync(String appId, int shuffleId) {
   public ShuffleDataDistributionType getDataDistributionType(String appId) {
     return shuffleTaskInfos.get(appId).getDataDistType();
   }
+
+  private void triggerFlush() {
+    synchronized (this.shuffleBufferManager) {
```
Comment (zuston) [inline server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:607]: Sorry, I can't get this point of this change. By the way, it we hold the lock of `ShuffleBufferManager`, do it effect the critical rpc request when sending shuffle-data from client. refer to: https://github.com/apache/incubator-uniffle/blob/53212923328194fafa5ae94aa216ab04f06fbd13/server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java#L120-L125.

Although I think this part is unreasonable because it will concurrent requests reshape to serial. Maybe this could be solved in another PR. But for current codebase, the `triggerFlush` will effect performance

**Comment by zuston** [comment]
> > From my side, I think the mechanism of requiring allocation seems like token bucket algorithm, the most difference is the bucket size depending on the free-memory, which is a dynamic bucket. Based on this, we should use the global lock when releasing or getting, this is the key to solve the problem mentioned in description.
> 
> +1

If this is right, maybe we'd better to have an abstraction to implement the throttle policy, instead of bounding to the `shuffleBufferManager`. 

Emm... This expands the scope of this PR. Feel free to discuss more.

**Comment by jerqi** [comment]
> > > From my side, I think the mechanism of requiring allocation seems like token bucket algorithm, the most difference is the bucket size depending on the free-memory, which is a dynamic bucket. Based on this, we should use the global lock when releasing or getting, this is the key to solve the problem mentioned in description.
> > 
> > 
> > +1
> 
> If this is right, maybe we'd better to have an abstraction to implement the throttle policy, instead of bounding to the `shuffleBufferManager`.
> 
> Emm... This expands the scope of this PR. Feel free to discuss more.

It's hottest path ..... if we could avoid using lock, why do we use it?

File: server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java (hunk 11 above)
Comment (zuston) [reply server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java:607]: > In current codebase, the triggerFlush is only called per rss.server.shuffleBufferManager.trigger.flush.interval, which should be 2-5 mins on server side. That shouldn't be too much overhead?

Yes, it wont.

> As for why triggerFlush is introduced in this PR, its main reason is to reduce UT changes for the behavior changes as preAllocatedSize is decreased in Grpc layer, rather than the cache data layer.

Got it.

> And also, I thought it would be better if we decoupled the flush logic with cacheShuffleData, which causes flush spikes, and frequent full gc.

+1.

**Comment by zuston** [comment]
> Do we have OOM?

Just supposing

**Comment by jerqi** [comment]
> > Do we have OOM?
> 
> Just supposing

So we shou l

**Comment by zuston** [comment]
After surfing the whole process of requiring/releasing pre-allocated size, I have a question that why the preAllocatedSize is added to two vars of `ShuffleBufferManager.usedMemory` and `ShuffleBufferManager.preAllocatedSize` in here (https://github.com/apache/incubator-uniffle/blob/53212923328194fafa5ae94aa216ab04f06fbd13/server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java#L242-L255).

And I still can't find the key of this pr to solve the negative preAllocatedSize. Could you help describe more? @advancedxy 

> Lock isn't the only mechinsm to avoid OOM.

Emm.. Yes. But in current codebase, the requiring pre-allocation operation is guarded by the global lock, which is shown in above code snippet. @jerqi

**Comment by jerqi** [comment]
I just don't want to increase extra lock.

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java [hunk 12]
```diff
@@ -258,6 +260,12 @@ public void sendShuffleData(SendShuffleDataRequest req,
           break;
         }
       }
+      // since the required buffer id is only used once, the shuffle client would try to require another buffer whether
+      // current connection succeeded or not. Therefore, the preAllocatedBuffer is first get and removed, then after
+      // cacheShuffleData finishes, the preAllocatedSize should be updated accordingly.
+      if (info.getRequireSize() > alreadyReleasedSize) {
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:266]: Should we remove this condition?

File: server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java [hunk 13]
```diff
@@ -229,25 +232,24 @@ public void sendShuffleData(SendShuffleDataRequest req,
       }
       final long start = System.currentTimeMillis();
       List<ShufflePartitionedData> shufflePartitionedData = toPartitionedData(req);
+      int alreadyReleasedSize = 0;
```
Comment (xianjingfeng) [inline server/src/main/java/org/apache/uniffle/server/ShuffleServerGrpcService.java:235]: `int` is enough now, but i think `long` is more safe in the future. But `int` is ok for me too.

File: common/src/main/java/org/apache/uniffle/common/ShufflePartitionedData.java [hunk 14]
```diff
@@ -49,4 +49,15 @@ public ShufflePartitionedBlock[] getBlockList() {
     return blockList;
   }
 
+  public int getTotalBlockSize() {
```
[the remark this answers is not in the document]
Comment (xianjingfeng) [reply common/src/main/java/org/apache/uniffle/common/ShufflePartitionedData.java]: Could we reuse this result?

https://github.com/apache/incubator-uniffle/blob/53212923328194fafa5ae94aa216ab04f06fbd13/server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBuffer.java#L63-L72

**Review by jerqi — APPROVED** [review]
